apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: pubsub
spec:
  licenseKeySecret:
    name: iris-key-secret-dev
  configSource:
    name: pubsub-common-cpf-cm
  imagePullSecrets:
    - name: harbor-pull-credentials
    - name: harbor-intersystems-credentials
  volumes:
    # configmaps
    - name: pubsub-configmaps-cm
      configMap:
        name: pubsub-configmaps-cm
    - name: pubsub-defaultsettings-cm
      configMap:
        name: pubsub-defaultsettings-cm
  topology:
    data:
      image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/iris:2024.2
      compatibilityVersion: '2024.2'
      mirrored: true
      podTemplate:
        spec:
          nodeSelector:
            px/enabled: 'true'
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2Gi
      irisDatabases:
        - name: PUBSUB_DATA
          directory: /irissys/data/IRIS/mgr/PUBSUB_DATA
          ecp: true
          mirrored: true
        - name: PUBSUB_CODE
          directory: /irissys/data/IRIS/mgr/PUBSUB_CODE
      irisNamespaces:
        - name: PUBSUB
          routines: PUBSUB_CODE
          globals: PUBSUB_DATA
      webgateway:
        image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/webgateway:2024.2
        replicas: 1
        loginSecret:
          name: webgateway-secret
        applicationPaths:
          # for accessing the mgmt portal of data
          - /csp
          - /csp/sys
          - /csp/bin
          - /csp/broker
          # for accessing the healthshare stuff
          - /csp/healthshare
          # pubsub portal
          - /pubsub/portal
          # vscode
          - /api
          - /api/atelier
        # this is needed for the sidecar web gateway, it is used in WG Server Access
        podTemplate:
          spec:
            resources:
              limits:
                cpu: 200m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 512Mi
            nodeSelector:
              px/enabled: 'true'
    compute:
      # image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/irishealth:2024.2
      image: harbor.443916233c2349241f52.kpnappfactory.nl/hex/hex-werkplekken-pubsub:1.0.0-001    
      compatibilityVersion: '2024.2'
      hpa:
        spec:
          minReplicas: 2
          maxReplicas: 3
          scaleTargetRef:
            kind: StatefulSet
            name: pubsub-compute
            apiVersion: apps/v1
      updateStrategy:
        type: RollingUpdate
      podTemplate:
        spec:
          # args:
          #   - '--after iris session IRIS < /home/irisowner/after-install.script'
          nodeSelector:
            px/enabled: 'true'
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2Gi
      volumeMounts:
      - name: pubsub-configmaps-cm
        mountPath: /home/irisowner/configmaps
      # - name: mkls-after-install
      #   mountPath: /home/irisowner/after-installs
      - name: pubsub-defaultsettings-cm
        mountPath: /home/irisowner/sysdefaults
      # - name: certificates-volume
      #   mountPath: /home/irisowner/certificates
    webgateway:
      image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/webgateway:2024.2
      replicas: 1
      loginSecret:
        name: webgateway-secret
      applicationPaths:
        # - /csp
        - /csp/sys
        - /csp/bin
        - /csp/broker
        - /csp/mmlogging
      # vscode
        - /api
      # webterminal
        - /terminal
        - /terminal-vscode
        - /terminalsocket
      # PUBSUB API
        - /pubsub/portal
      podTemplate:
        spec:
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1Gi
          nodeSelector:
            px/enabled: 'true'
    arbiter:
      image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/arbiter:2024.2
